#! /bin/sh

#  |
#  __ \    __|   __ \     \ \  \   / __ `__ \
#  |   | \__ \  |   |      \ \  \ / |   |   |
# _.__/  ____/   __/        \_/\_/ _|  _|  _|
#              _|
# binary space partitioning window manager

# > bspc configs
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep bspswallow || bspswallow &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width            3
bspc config window_gap              6
bspc config top_padding             32
bspc config bottom_padding          0

bspc config focused_border_color    "#e69875"
bspc config normal_border_color     "#514045"
bspc config presel_feedback_color   "#e69875"

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true

bspc rule -a mpv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# > Autostart
exec $HOME/.config/bspwm/autostart.sh &
