#! /bin/sh

#  |
#  __ \    __|   __ \     \ \  \   / __ `__ \
#  |   | \__ \  |   |      \ \  \ / |   |   |
# _.__/  ____/   __/        \_/\_/ _|  _|  _|
#              _|
# binary space partitioning window manager

#--------------------#
# bspc and important #
#--------------------#
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep bspswallow || bspswallow &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width            3
bspc config window_gap              5
bspc config top_padding             33
bspc config bottom_padding          0

bspc config focused_border_color    "#575268"
bspc config normal_border_color     "#1A1826"
bspc config presel_feedback_color   "#F2CDCD"

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true

bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
#bspc rule -a Alacritty state=pseudo_tiled
#bspc rule -a neovide state=pseudo_tiled

#-----------#
# Autostart #
#-----------#
exec $HOME/.config/bspwm/autostart.sh &
