#!/usr/bin/env sh
#-Auto Start DWM ONLY
picom --vsync --backend glx &
nitrogen --set-auto "$HOME/Pictures/Backgrounds/wallpaper-alt.png" &

xss-lock -l env XSECURELOCK_SHOW_USERNAME=0 XSECURELOCK_SHOW_HOSTNAME=0 XSECURELOCK_FONT=Jetbrains\ Mono XSECURELOCK_PASSWORD_PROMPT=time_hex xsecurelock &

lxpolkit &

# Keyboard Layout = layout-model
setxkbmap -layout br -model abnt2 &

# Mouse
xinput set-button-map "Compx 2.4G Receiver Mouse" 1 2 3 4 5 6 7 2 9 &

# Touchpad
xinput --set-int-prop "ELAN0504:00 04F3:3091 Touchpad" "libinput Natural Scrolling Enabled" 8 1 &
xinput set-prop "ELAN0504:00 04F3:3091 Touchpad" "libinput Disable While Typing Enabled" 1 &
xinput set-prop "ELAN0504:00 04F3:3091 Touchpad" "libinput Tapping Enabled" 1 &


# Apps

#exec $HOME/.config/polybar/scripts/startup.sh &


exec $HOME/.config/dunst/scripts/startup.sh &
#pgrep dunst || dunst &


pgrep conky || conky &

#pgrep glava || glava -d & # too much cpu usage

pgrep nm-applet || nm-applet &

pgrep xfce4-clipman || xfce4-clipman &

pgrep redshift-gtk || redshift-gtk &

pgrep blueman-applet || blueman-applet &

#pgrep dwmblocks || dwmblocks # set in config.h
