#!/bin/sh
# What to run when leftwm starts up

#------#
# Main #
#------#
pgrep blueman-applet || blueman-applet &
exec $HOME/.config/dunst/scripts/startup.sh &
exec $HOME/.config/polybar/scripts/startup.sh &
nitrogen --set-auto "$HOME/Pictures/Backgrounds/wallpaper.png" &
pgrep picom || picom --vsync --backend glx &
pgrep redshift-gtk || redshift-gtk &
pgrep xfce4-clipman || xfce4-clipman &
xss-lock -l env XSECURELOCK_SHOW_USERNAME=0 XSECURELOCK_SHOW_HOSTNAME=0 XSECURELOCK_FONT=Jetbrains\ Mono XSECURELOCK_PASSWORD_PROMPT=time_hex xsecurelock &

#---------#
# Devices #
#---------#
setxkbmap -layout br -model abnt2 &
xinput --set-int-prop "ELAN0504:00 04F3:3091 Touchpad" "libinput Natural Scrolling Enabled" 8 1 &
xinput set-button-map "Compx 2.4G Receiver Mouse" 1 2 3 4 5 6 7 2 9
xinput set-prop "ELAN0504:00 04F3:3091 Touchpad" "libinput Disable While Typing Enabled" 1 &
xinput set-prop "ELAN0504:00 04F3:3091 Touchpad" "libinput Tapping Enabled" 1 &
